### ISSUE TITLE
Questions about development flow

### ISSUE THREAD

**Issue by 4imble** [jakkn/nwn-devbase#18]
Hi there, I just read the [INTRODUCTION](https://github.com/jakkn/nwn-devbase/blob/master/INTRODUCTION.md) (loved the  illustrations).

I'm still a little unsure how to actually make a change and test it: 
It'd be awesome if you could do a video or at least explain these steps if you don't mind?.

- Get code from github (understood)
- Make a new area or even just add a new placeable to an area. 
   - Are you using the toolset here and loading the unpacked assets somehow or are you repacking from the sourcecode and using that inside the toolset.
   - If you are on linux, how are you running the toolset, wine?
- Make some nwscript changes
   - Are you using an external editor like VS:Code or are you using the toolset here too
- Testing the changes
   - Are you repacking to test the changes, if on windows how are you doing this (docker wont mount from windows to linux volumes without complications as far as I can tell)
- Submit to Git (understood)

**Comment by jakkn** [comment]
Sure! I can't promise a video anytime soon, but I'll type out the intended workflow.

As you have understood, there are two ways of making changes to the module sources; change the packed module (.mod file) doing work in the toolset, and on the extracted raw resources (YAML files) working in a text editor. When modifying module sources it is important to not mix these two approaches, as any work done in the toolset is not reflected in the YAML until the `extract` command is run, and you risk losing work if you edit the same resource in the toolset and in a text editor at the same time, unless you know what you're doing.

> * Make a new area or even just add a new placeable to an area.
>   - Are you using the toolset here and loading the unpacked assets somehow or are you repacking from the sourcecode and using that inside the toolset.

When making new areas, or generally when editing gff resources - gff meaning areas, creatures, waypoints, encounters, etc - use the toolset. The process of using the toolset can be summed up in these steps
```
git pull
nwn-build pack
```
Load the module with the toolset as explained under [README#Symlinks](https://github.com/jakkn/nwn-devbase/#symlinks).
Operate the toolset as normal. Changes in the toolset are stored to .mod file which will have to be extracted when you're done.
```
nwn-build extract
git add -A
git commit
```

> *
>    - If you are on linux, how are you running the toolset, wine?

Yes, use wine.

> * Make some nwscript changes
>    - Are you using an external editor like VS:Code or are you using the toolset here too

Yes, I prefer editing nwscript in VS Code. There's a plugin that provides syntax highlighting, and general code navigation is much better. I think Intellisense also works to some degree. I also do occasional changes to YAML files from VS Code, to change text, fix typos and edit various values to areas and creatures.

> * Testing the changes
>    - Are you repacking to test the changes, if on windows how are you doing this (docker wont mount from windows to linux volumes without complications as far as I can tell)

I make changes, run `nwn-build pack`, and load the module. When the module runs in a docker container it's fairly simple to restart by attaching to the container and stopping nwserver. docker-compose should bring it right up again if the service is set to restart.

Running `nwn-build` works both natively and with the docker container on all platforms. There are some quirks under Windows, but it generally works. If you're using docker-toolbox remember that volume mounts only work from the user directory (%USERPROFILE%).

**Comment by 4imble** [comment]
Very well responded, thank you for taking the time to do that. It's much clearer in my mind how to use this now. Thanks again.

**Comment by jakkn** [comment]
Np! Hopefully it can be of help others as well.

Archiving.
