### ISSUE TITLE
Add ability to specify encoding for nwn-gff and nwn_tlk

### ISSUE THREAD

**Issue by Mingun** [jakkn/nwn-devbase#25]
Some localizations of NWN do not use own language code, and instead use code 0 (English). For example, Russian localization. In order that when converting the text did not turn into mojibakes, it is necessary to specify encoding, but at the moment it cannot be made without editing of the source code of scripts

**Comment by jakkn** [comment]
Hi @Mingun, thank you for raising the issue. Can you give an example of the command and arguments you would like to run?

**Comment by Mingun** [comment]
Hi @jakkn. This is diff that I applied for my purposes. I know Ruby insufficiently to transfer arguments from one script to another, otherwise I would be offer PR :). But also so too many new tools should be studied to begin work on the versioned NWN module... Only an opportunity to transmit encoding parameter from main `build.rb` script is necessary, maybe from `.nwnproject/config.rb.in`:
```diff
 extract.rake | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/extract.rake b/extract.rake
index df8bad7..ffd10f8 100644
--- a/extract.rake
+++ b/extract.rake
@@ -17,6 +17,7 @@ SCRIPTS_DIR = Pathname.new ENV['SCRIPTS_DIR']
 GFF_SOURCES = FileList[to_forward_slash GFF_CACHE_DIR.join("*.*")].exclude(/\.n[cs]s$/)
 YML_TARGETS = FLAT_LAYOUT ? GFF_SOURCES.pathmap("#{SRC_DIR}/%f.yml") : GFF_SOURCES.pathmap("#{SRC_DIR}/%{.*,*}x/%f.yml") { |ext| ext.delete('.') }
 DIRS = Set.new.merge GFF_SOURCES.pathmap("%{.*,*}x") { |ext| ext.delete('.') }
+ENCODING = "windows-1251"
 
 desc 'Create dir tree and convert to yml'
 task :yml => [:create_folders, :gff2yml]
@@ -36,7 +37,7 @@ desc 'Convert gff to yml'
 multitask :gff2yml => YML_TARGETS
 
 rule '.yml' => ->(f){ source_for_yml(f) } do |t|
-	system "nwn-gff", "-i", "#{t.source}", "-lg", "-o", "#{t.name}", "-r", to_forward_slash(SCRIPTS_DIR.join("truncate_floats.rb").to_s)
+	system "nwn-gff", "-i", "#{t.source}", "-lg", "-o", "#{t.name}", "--encoding", "#{ENCODING}", "-r", to_forward_slash(SCRIPTS_DIR.join("truncate_floats.rb").to_s)
 	FileUtils.touch "#{t.name}", :mtime => File.mtime("#{t.source}")
 end
 
```
It is very probable that it is not all changes which need to be made, back I did not reach pack stage yet

**Comment by Mingun** [comment]
Also the possibility to recode nss scripts to UTF-8 is required. For example, in Russian localization the text in scripts for NWN1 must be in windows-1251, otherwise editor not display it correctly. But now the standard de facto is UTF-8 and I want to store scripts in VCS in UTF-8

**Comment by jakkn** [comment]
--encoding flag exposed in 0cee760fc70d8bb6f7a75d0b1f8fa31de81e2d68

**Comment by Mingun** [comment]
Thanks! I already and itself began to investigate opportunities and was almost ready to make PR. However you did not consider that the encoding needs also to be supplied to the `pack` command:
```diff
 pack.rake | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/pack.rake b/pack.rake
index ad8ad2b..119b4a4 100644
--- a/pack.rake
+++ b/pack.rake
@@ -10,6 +10,7 @@ task :default => :gff
 
 SRC_DIR = Pathname.new ENV['SRC_DIR']
 GFF_CACHE_DIR = Pathname.new ENV['GFF_CACHE_DIR']
+ENCODING = ENV['ENCODING']
 
 YML_SOURCES = FileList[to_forward_slash SRC_DIR.join("**/*.yml")].exclude(/n[cs]s$/)
 GFF_TARGETS = YML_SOURCES.pathmap("#{GFF_CACHE_DIR}/%n")
@@ -22,7 +23,7 @@ task :gff => [GFF_CACHE_DIR.to_s, :yml2gff]
 multitask :yml2gff => GFF_TARGETS
 
 rule( /\.(?!yml)[\w]+$/ => ->(f){ source_for_gff(f) }) do |t|
-	system "nwn-gff", "-i", "#{t.source}", "-o", "#{t.name}", "-kg"
+	system "nwn-gff", "-i", "#{t.source}", "-o", "#{t.name}", "-kg", "--encoding", "#{ENCODING}"
 	FileUtils.touch "#{t.name}", :mtime => File.mtime("#{t.source}")
 end
 
```

**Comment by jakkn** [comment]
Ah crap, I forgot all about this. Fixing asap.
