### ISSUE TITLE
Dockerized nwn-build init fails to create subdirs and config files 

### ISSUE THREAD

**Issue by GenMalfunction** [jakkn/nwn-devbase#33]
Host OS = Linux Mint 19.1
Docker = $ docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:00 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

CLI Output = 
-=-=-=-=-=-=
/home/devbase/build$ nwn-build init
[INFO] Creating /home/devbase/build/.nwnproject
[INFO] Creating /home/devbase/build/.nwnproject/.gitignore
/var/lib/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
Module filename (module.mod):

/var/lib/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
Create default module directory (/home/devbase/build/server/modules)? [Y/n]:
y
markn@jupiterstationprime:/home/devbase/build$
-=-=-=-=-=-=-=

Neither .nwnproject nor .nwnproject/.gitignore are in fact created, whether ./server/modules exists beforehand or not.

Would love love LOVE to get this running, as I'm coming back to NWN:EE, and late to the party as a .mod tinkerer.

Also, FWIW, I may be able to help with the docs for OSX, as I have one available.

**Comment by jakkn** [comment]
Hi, thank you for your feedback. Can you paste in the exact `docker run` command you use? I've had some issues where files and folders are created in the home directory, but only when the tool runs natively. With docker all modifications to the file system will be contained to the folder mount.

As a side note, while I personally still use this tool it is largely unmaintained in terms of fixing the larger issues. I'd rather spend time on a rewrite than trying to fix code that was stitched together quick to fill an immediate need. [Nasher](https://github.com/squattingmonk/nasher) is a more mature, faster, and feature rich alternative that'll get you up and running quicker.

**Comment by GenMalfunction** [comment]
Thanks for the lighting-fast reply, and understood about maintenance mode on this code (fwiw, I already tried Nasher and getting it to work in my environment has eluded me thus far -- Linux, Steam NWN Client, running Aurora via WINE, i'm a mess!)

Anyway, my CLI is set up per your docs, AFAICT:

nwn-build='docker run --rm -it --user 1000:999 -v "$(pwd):/home/markn/Desktop/nwn-build" jakkn/nwn-devbase'

WHERE:
1000 = my numeric UID
999 = my numeric primary GUID
pwd = /home/devbase/build (owned by 1000:999)
And i've even created /home/devbase/bild/server/modules/ as well as copied my working file to that path as "module.mod"
Also tried manually creating /home/devbase/build/.nwnproject/ and still no luck

**Comment by jakkn** [comment]
Hehe, sounds like my own environment. I can confirm the tool works on both linux and windows so there's probably just a small quirk here. See if you can initialize the folders with `nwn-build init`. If no command is passed it defaults to `pack`, which will do nothing before you have the folder structure up (the default should really be to print usage notes, I guess that should be changed). If it still doesn't work you can print the running environment with `nwn-build -v`. Paste that here for further debugging.

**Comment by squattingmonk** [comment]
Obviously, this isn't an appropriate place to discuss nasher, but if you open an issue on the nasher repo or message me on Discord, I can help you out. Relevant links [here](https://github.com/squattingmonk/nasher#getting-help).

**Comment by GenMalfunction** [comment]
Thanks @jakkn for trying to help me along -- i took yours and @squattingmonk's suggestions and gave Nasher another go. Got that running on nth try.

If you ever decide to refactor this project, I would be happy to be a tester for you.
