### ISSUE TITLE
tons of merge conflicts

### ISSUE THREAD

**Issue by deltreey** [jakkn/nwn-devbase#6]
this doesn't really seem to solve the problem of multiple people working together at all.  I can run

```
./pack
open toolset
build module
save module
exit toolset
./unpack
```

and end up with over 100 binary files changed in git.  As a result, every merge is filled with conflicting binary files, which creates 0 ability to resolve any changes that the two people were working on.  I spent hours setting this up and I don't know if I missed something or it's just not intended for that, but now I basically have an unpackable module that I can't change anyway... help!

The 100+ files appear to be all `.git` files named after areas.  I'm adding them to my gitignore with the hopes that it'll fix it, but any insight would be great!

Update:

Seems that those .git files identify all the areas, and without them the project has 0 areas :(.  Looks like I'll need to keep looking.

**Comment by jakkn** [comment]
Hi @deltreey, thank you for opening an issue. Late reply as I am on holiday.

The binaries makes merging more difficult than it has to be, and I'm working on #1 to solve this.

.git files should not be ignored as the files are used for areas like you noticed. Why so many .git files changed I do not know, it would help to know exactly what changed. I can help you sort this out if you are still interested. If you are, please respond here and make a note of which operating system you are using. You will have to extract the binaries and diff the content.

**Comment by deltreey** [comment]
I have done a lot of research on this now.  Changing your scripts I was easily able to auto-convert the binaries to XML and that creates what appears to be nice diffable files.

Unfortunately when I convert them back to a mod file it is corrupt and won't build.  I'm wondering if this is a known issue with NWNtools

**Comment by jakkn** [comment]
Good! I would have to test the script to try to reproduce, though the first thing that comes to mind is that going from XML to MOD is a two step process where you have to make sure to first run XmlToGff and then GffToMod, as documented in the NWNTools [README](https://github.com/jakkn/nwn-devbase/blob/master/nwntools/readme.html).

**Comment by jakkn** [comment]
And there shouldn't be any known issues with NWNTools to my knowledge.

**Comment by deltreey** [comment]
Here's what that would look like if I understood the docs.

``` batch
:: ...

CD ..\nwntools
CALL XmlToGff.cmd ..\tmp ..\tmp\*
CALL ModPacker.cmd ..\tmp ..\packed\<mod_name>.mod

:: ...
```

I'm going to take another look at the tools list and see if I can figure out where I'm going wrong that's causing the mod to pack incorrectly.  If I can get this to work, I will gladly put in a pull request with my pack and unpack scripts so that you can close your other issue as well on this.

For reference, here's the majority of the relevant changes to the unpack script (windows version)

``` batch
CALL ModToXml.cmd ..\packed\<mod_name>.mod ..\tmp

:: ...

ECHO Moving sources into unpacked\ ...
CD ..\tmp
FOR %%i IN (*.xml) DO (
    IF EXIST %%i (
        SETLOCAL enabledelayedexpansion
        SET name=%%~ni
        SET ext=!name:~-3!
        MD ..\unpacked\!ext!
        MOVE *.!ext!.xml ..\unpacked\!ext! >nul
        ENDLOCAL
    )
)

FOR %%i IN (*.ncs,*.nss) DO (
    IF EXIST %%i (
        SETLOCAL enabledelayedexpansion
        SET ext=%%~xi
        SET ext=!ext:~1!
        MD ..\unpacked\!ext!
        MOVE *!ext! ..\unpacked\!ext! >nul
        ENDLOCAL
    )
)

:: ...
```

**Comment by jakkn** [comment]
Solved by using ruby library nwn-lib. See build.rb.
